server:
 port: 8080
  
spring:  application.name: gateway
  cloud:
   gateway:
    default-filters:
    - PrefixPath=/
    routes:
    #==== This is a comment =====
    - id: flashcard
      uri: http://localhost:8089
      predicates:
      - Path=/flashcard/**
    #====================
    - id: quiz
      uri: http://localhost:8090
      predicates:
      - Path=/quiz